// <auto-generated />
namespace OnlineShopMASK.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RATING : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RATING));
        
        string IMigrationMetadata.Id
        {
            get { return "202008261450341_RATING"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
